### ISSUE TITLE
merge into core?

### ISSUE THREAD

**Issue by dillongreen** [xpressivecode/iron-router-auth#1]
This is great. I'd reckon it's useful for many using iron-router but then they might never know about it simply because they'll not come across this separate package which is why I'd say it would make sense to ask Chris to merge it into core no?

**Comment by xpressivecode** [comment]
I was going to wait until some feedback came in (if any). I wanted to see if it's suitable first. It fits my needs, but it might not work for other peoples situations.

I agree though. It would be nice to see something included in iron-router that does away with everyone having to write their own auth filter.

I'll wait until I receive some more feedback before approaching Chris.

Thanks!

**Comment by dillongreen** [comment]
Understood, makes sense... (why not ask on the mailing list?) Thanks for doing it, I already find it good as is :)

**Comment by xpressivecode** [comment]
Hey @markusgattol I started up a new feature design issue over at iron router if you care to weigh in on it's implementation etc.

https://github.com/EventedMind/iron-router/issues/363

thanks for the encouragement and I'm glad it works well for you.
