### ISSUE TITLE
Setting layout property in loginRequired does not work properly.

### ISSUE THREAD

**Issue by pbeets** [xpressivecode/iron-router-auth#17]
So my login page has a different layout than the logged in views. However when I set the following:

<pre><code>
loginRequired: {
    name: 'login',
    layout: 'gateway'
},
</code></pre>

it doesn't actually redirect with the right layout. After digging around I found that shouldRoute is set to true on default, and because of that it completely skips the part about setting the layout. This seems odd as I do want it to redirect, but redirect it with the proper layout.

The page renders properly if I set <code>shouldRoute: false</code> however this is undesired behavior because I have other hooks on that route and would like to use the login route.

<pre><code>
if(options.loginRequired.shouldRoute){
    return this.redirect(options.loginRequired.name);       
}else{
    if(options.loginRequired.layout){
        this.layoutTemplate = options.loginRequired.layout;
    }
    this.render(options.loginRequired.name);
    this.renderRegions();
    return pause();
}
</code></pre>

**Comment by pbeets** [comment]
Added a pull request https://github.com/XpressiveCode/iron-router-auth/pull/18 to fix this issue.

**Comment by xpressivecode** [comment]
merged #18 so this is fixed now.

thanks @pbeets

**Comment by pbeets** [comment]
Can you also update the release to the latest version? Doing a meteorite update still loads the older commit.
