### ISSUE TITLE
Compatibility with meteor 0.9.x

### ISSUE THREAD

**Issue by fuatsengul** [xpressivecode/iron-router-auth#20]
This package now incompatible with meteor 0.9x versions.
Can you work on it please?

**Comment by jhuenges** [comment]
Would be great! Love this package :)

**Comment by jhuenges** [comment]
For refernce: https://hackpad.com/Migrating-Packages-zN0we9sIjkH

**Comment by fuatsengul** [comment]
I've added the files that I needed into my project manually. Hope you fix this soon and we use in the proper way.

**Comment by jhuenges** [comment]
@fuatsengul can you make a pull request?

**Comment by wbashir** [comment]
+1

**Comment by fuatsengul** [comment]
I did! and tried to solve the issue.
This was my first folks! 
Hope it's well..

**Comment by jhuenges** [comment]
Looks nice :) Good job

Edit: https://atmospherejs.com/fuatsengul/iron-router-auth

**Comment by fuatsengul** [comment]
Merged and closed..

**Comment by jhuenges** [comment]
I cant find the version from @XpressiveCode  on atmopshere ... Maybe you need to republish the package?
