### ISSUE TITLE
Package migrated to another repository?

### ISSUE THREAD

**Issue by LeCoupa** [xpressivecode/iron-router-auth#22]
When running `meteor search iron-router-auth`, we get:

```
zimme:iron-router-auth  Authentication and authorization for iron:router
```

This seems to be the most updated version of `iron-router-auth`.

**Comment by xpressivecode** [comment]
Yes, there have been people far more active in the community that have created better packages to handle route authorization. I haven't updated this in ages. I'll look into either removing the package from atmosphere or marking it as deprecated in favour of using what @zimme has put together.
