### ISSUE TITLE
redirectOnLogin problem

### ISSUE THREAD

**Issue by zimme** [xpressivecode/iron-router-auth#5]
I'm having trouble using the redirectOnLogin feature

router.coffee

``` coffee
Router.map ->
    @route 'signIn',
        path: 'sign-in'
        redirectOnLogin: true
```

signin.coffee

``` coffee
Template.signIn.events
    'submit #signIn': (event, ui) ->
        event.preventDefault()
        email = ui.find('#email').value
        password = ui.find('#password').value
        Meteor.loginWithPassword email, password, (error) ->
            if error
                console.log error
```

router.coffee

``` coffee
Router.map ->
    @route 'listUsers',
        path: 'users'
        waitOn: ->
            if Meteor.userId()
                @subscribe 'allUserData'
        data:
            users: ->
                Users.find()
        loginRequired: 'signIn'
```

using this setup i get redirected to the signIn route when trying to list users and signIn action signs in as expected but there's no redirect action taken automagically which is what should happen if i'm understanding the docs correct?

This is the main reason for me starting the thread about the render vs redirect idea

**Comment by xpressivecode** [comment]
Hi @zimme can you let me know which version of iron-router and meteor you're using. I just want to try and replicate the issue. 

The redirect relies on `Session` and `Router.current().path`.

**Comment by zimme** [comment]
I'm using meteor's Blaze-rc0 release and iron-router's blaze-integration branch, if you're having trouble with iron-router complaining about this.stop() you can test with my fork
https://github.com/zimme/iron-router-auth
that is updated to support blaze-integration branch

**Comment by xpressivecode** [comment]
@zimme is this still an issue for you?

I've upgraded to use the latest version of iron-router + meteor 8.0 and the redirect works for me.

**Comment by zimme** [comment]
Dunno, using the render option. But I'll check tomorrow, I've had too many beers to try it now

**Comment by xpressivecode** [comment]
closing for now

**Comment by zimme** [comment]
Fine with me, I'll just re-open in case om emergency :p
