### ISSUE TITLE
Integrate with meteor-roles

### ISSUE THREAD

**Issue by zimme** [xpressivecode/iron-router-auth#7]
I was thinking if it would be a good idea to make this package use meteor-roles if available, making it possible to specify roles for a specific route and maybe even assign specific template's depending on roles, or should this be kept inside templates using meteor-roles helpers?

Any thoughts? @XpressiveCode

**Comment by wbashir** [comment]
+1, i was just going through trying to find a way to integrate these two packages.

**Comment by xpressivecode** [comment]
@warsamebashir  did you have any luck, or have you not tried anything as of yet?

This is an interesting thought. How would you want to see the api handle this? Given the loginRequired object as it stands today.

``` js
loginRequired: {
  ... // normal props here
  roles: [
    { role: 'admin', layout: 'admin' },
    { role: 'user', layout: 'main' }
  ]
}

//or 

loginRequired: {
  ... // normal props here
  role: 'admin'
}
```

I have never used the meteor-roles package. I also tend to keep new feature integration with a large amount of complexity to a minimum when I don't personally use them as I find I'm not invested in it, so it makes supporting it difficult. That and it's harder for me to keep that particular feature up to date when I'm not relying on it. 

Can either of you two help provide some insight into what the api should look like and how you would expect to implement it? 

Thanks

**Comment by wbashir** [comment]
I haven't fully dived into it yet but the meteor-roles package has existing role checkers that might be useful, i would imagine the API much like this one, takes in as an argument, an array `[]` of roles that must be true for the current user before the route is executed (onBeforeAction).

**Comment by joshuaauger** [comment]
I have a fork that does this, but it is not a great way of handling it, would anyone look at it for me?

**Comment by wbashir** [comment]
@joshuaauger You should make a pull request if you can, I am still looking for this

**Comment by xpressivecode** [comment]
@warsamebashir with the new `isLoggedIn` function that you can override, would it be possible for you to wrap your role check in there? I know it's not as integrated as you would like. But at least it isn't a show stopper?

**Comment by wbashir** [comment]
@XpressiveCode Oh Awesome! Can I use that `isLoggedIn` function at a global level: `Router.configure` and override it where needed or use in my `ApplicationController`.

**Comment by xpressivecode** [comment]
It happens at the route definition. So while that isn't ideal, you could in theory create a global function and then just reference it. In every definition. 

``` js
var global_function = function(){
// check if user is logged in and if they have the correct role
};
...
// route definition goes here, I've only included the relevant line as the readme has full examples
isLoggedIn: global_function
```

**Comment by wbashir** [comment]
@zimme Does this work now in `Router.Controller` and not just available on the route ?

**Comment by zimme** [comment]
I have no idea. I don't use this package any more because it was so inactive I created my own package
[zimme:iron-router-auth](/zimme/meteor-iron-router-auth).

It's a re-write that uses iron:router's plugin system instead and I added a cleaner way of handling authorization too. (allow/deny rules).
