### ISSUE TITLE
isLoggedIn method extend

### ISSUE THREAD

**Issue by juliancwirko** [xpressivecode/iron-router-auth#9]
This works for me:

function isLoggedIn() {
                if(options.isLoggedIn !== undefined)
                    return options.isLoggedIn();
                else
                    return (Meteor.user() !== null);
            }

and not with Router.options....

function isLoggedIn() {
                if(Router.options.isLoggedIn !== undefined)
                    return Router.options.isLoggedIn();
                else
                    return (Meteor.user() !== null);
            }

**Comment by joshuaauger** [comment]
Thanks, I just issued a pull request for the author.

**Comment by xpressivecode** [comment]
thanks, merged
